// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYcR7SNbFMd-Mwm43bOVBb4chZ-NwQThg',
    appId: '1:82779433934:web:61371be9f3401f798a999f',
    messagingSenderId: '82779433934',
    projectId: 'stridemind-a3716',
    authDomain: 'stridemind-a3716.firebaseapp.com',
    storageBucket: 'stridemind-a3716.firebasestorage.app',
    measurementId: 'G-FTRC00QHW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1QmG2ckuIo8pTynVuOK-HR9OkN-NjWro',
    appId: '1:82779433934:android:8d26eefb004058b88a999f',
    messagingSenderId: '82779433934',
    projectId: 'stridemind-a3716',
    storageBucket: 'stridemind-a3716.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjRbuSVb7hOPN_Ujb8-z0ct2NmOjA0QkQ',
    appId: '1:82779433934:ios:289657c7b27a9bd48a999f',
    messagingSenderId: '82779433934',
    projectId: 'stridemind-a3716',
    storageBucket: 'stridemind-a3716.firebasestorage.app',
    iosBundleId: 'com.example.stridemind',
  );
}
